os:
  - linux
  - osx
language: ruby
env:
#  global:
#    - MAKEFLAGS="-j 2"
  matrix:
    - PACKAGE=""
    - PACKAGE=autoconf
    - PACKAGE=automake
    - PACKAGE=bzip2
    - PACKAGE=curl
    - PACKAGE=emacs
    - PACKAGE=expat
    - PACKAGE=gettext
    - PACKAGE=git
    - PACKAGE=glib
    - PACKAGE=libevent
    - PACKAGE=libffi
    - PACKAGE=libtool
    - PACKAGE=lua
    - PACKAGE=m4
    - PACKAGE=mercurial
    - PACKAGE=mosh
    - PACKAGE=ncurses
    - PACKAGE=openssl
    - PACKAGE=pkg-config
    - PACKAGE=protobuf
    - PACKAGE=python
    - PACKAGE=python3
    - PACKAGE=readline
    - PACKAGE=rubygems
    - PACKAGE=screen
    - PACKAGE=sl
    - PACKAGE=sshrc
    - PACKAGE=stow-get
    - PACKAGE=stow
    - PACKAGE=termcap
    - PACKAGE=texinfo
    - PACKAGE=tmux
    - PACKAGE=unzip
    - PACKAGE=vim
    - PACKAGE=wdiff
    - PACKAGE=wget
install:
  - 'if [ -z "$PACKAGE" ];then export INST_DIR="$HOME/usr/local";fi'
  - export PATH="$INST_DIR/bin:$PATH"
  - export LD_LIBRARY_PATH="$INST_DIR/lib64:$INST_DIR/lib:$LD_LIBRARY_PATH"
  - 'if [ -z "$PACKAGE" ];then echo "packages=(autoconf)" > ~/.stow-get;fi'
  - 'if [ -z "$PACKAGE" ];then mkdir conf_dir;fi'
  - 'if [ -z "$PACKAGE" ];then echo "packages=(ed)" > ./conf_file;fi'
  - 'if [ -z "$PACKAGE" ];then echo "isnt_type=gnu" > ./conf_dir/ed.sh;fi'
script:
  - 'if [ -n "$PACKAGE" ];then travis_wait 60 ./bin/stow-get install $PACKAGE;fi'
  - 'if [ -z "$PACKAGE" ];then ./bin/stow-get help;fi'
  - 'if [ -z "$PACKAGE" ];then ./bin/stow-get version;fi'
  - 'if [ -z "$PACKAGE" ];then ./bin/stow-get install -V;fi'
  - 'if [ -z "$PACKAGE" ];then ls "$INST_DIR/stow";fi'
  - 'if [ -z "$PACKAGE" ];then ls "$INST_DIR/stow/current";fi'
  - 'if [ -z "$PACKAGE" ];then ./bin/stow-get uninstall screen;fi'
  - 'if [ -z "$PACKAGE" ];then ls "$INST_DIR/stow";fi'
  - 'if [ -z "$PACKAGE" ];then ls "$INST_DIR/stow/current";fi'
  - 'if [ -z "$PACKAGE" ];then ./bin/stow-get list;fi'
  - 'if [ -z "$PACKAGE" ];then ./bin/stow-get packages;fi'
  - 'if [ -z "$PACKAGE" ];then ./bin/stow-get info screen;fi'
  - 'if [ -z "$PACKAGE" ];then ./bin/stow-get latest $(ls share/stow-get/*sh|cut -d"/" -f3|sed "s/.sh$//");fi'
  - 'if [ -z "$PACKAGE" ];then ./bin/stow-get install -c ./conf_file -d ./conf_dir;fi'
  - 'if [ -z "$PACKAGE" ];then echo "target_postfix=test" >> share/stow-get/autoconf.sh;fi'
  - 'if [ -z "$PACKAGE" ];then ./bin/stow-get install autoconf;fi'
  - 'if [ -z "$PACKAGE" ];then ls "$INST_DIR/stow";fi'
  - 'if [ -z "$PACKAGE" ];then ./bin/stow-get cleanup;fi'
  - 'if [ -z "$PACKAGE" ];then ls "$INST_DIR/stow";fi'
  - 'if [ -z "$PACKAGE" ];then ls "$INST_DIR/stow/current";fi'
