os:
  - linux
  - osx
language: ruby
env:
#  global:
#    - MAKEFLAGS="-j 2"
  matrix:
    - PACKAGE=stow-get
    - PACKAGE=stow
install:
  - export PATH="$INST_DIR/bin:$PATH"
  - export LD_LIBRARY_PATH="$INST_DIR/lib64:$INST_DIR/lib:$LD_LIBRARY_PATH"
script:
  - which texi2html
  - travis_wait 60 ./bin/stow-get -V install $PACKAGE
