language: python
before_install:
  - export INST_DIR="$HOME/usr/local"
  - export PATH="$INST_DIR/bin:$PATH"
  - export LD_LIBRARY_PATH="$INST_DIR/lib64:$INST_DIR/lib:$LD_LIBRARY_PATH"
install:
  - echo "PACKAGES=(git screen vim)" > ~/.stow-get
script:
  - ./bin/stow-get install -V
  - ./bin/stow-get install $(ls share/stow-get/*sh|cut -d"/" -f3|sed "s/.sh$//")
  - ls "$INST_DIR/stow"
