os:
  - linux
  - osx
language: ruby
env:
  global:
    - MAKEFLAGS="-j 2"
  matrix:
    - PACKAGE=""
    - PACKAGE=autoconf
    - PACKAGE=automake
    - PACKAGE=bzip2
    - PACKAGE=curl
    - PACKAGE=expat
    - PACKAGE=gettext
    - PACKAGE=git
    - PACKAGE=glib
    - PACKAGE=libevent
    - PACKAGE=libffi
    - PACKAGE=libtool
    - PACKAGE=lua
    - PACKAGE=m4
    - PACKAGE=mercurial
    - PACKAGE=mosh
    - PACKAGE=ncurses
    - PACKAGE=openssl
    - PACKAGE=pkg-config
    - PACKAGE=protobuf
    - PACKAGE=python
    - PACKAGE=readline
    - PACKAGE=rubygems
    - PACKAGE=screen
    - PACKAGE=sl
    - PACKAGE=stow-get
    - PACKAGE=stow
    - PACKAGE=termcap
    - PACKAGE=texinfo
    - PACKAGE=tmux
    - PACKAGE=unzip
    - PACKAGE=vim
    - PACKAGE=wget
install:
  - '[ -z "$PACKAGE" ] echo "packages=(autoconf)" > ~/.stow-get'
  - '[ -z "$PACKAGE" ] mkdir conf_dir'
  - '[ -z "$PACKAGE" ] echo "packages=(wdiff)" > ./conf_file'
  - '[ -z "$PACKAGE" ] echo "isnt_type=gnu" > ./conf_dir/wdiff.sh'
script:
  - '[ -n "$PACKAGE" ] travis_wait 30 ./bin/stow-get install $PACKAGE'
  - '[ -z "$PACKAGE" ] ./bin/stow-get help'
  - '[ -z "$PACKAGE" ] ./bin/stow-get version'
  - '[ -z "$PACKAGE" ] ./bin/stow-get install -V'
  - '[ -z "$PACKAGE" ] ls "$INST_DIR/stow"'
  - '[ -z "$PACKAGE" ] ls "$INST_DIR/stow/current"'
  - '[ -z "$PACKAGE" ] ./bin/stow-get uninstall screen'
  - '[ -z "$PACKAGE" ] ls "$INST_DIR/stow"'
  - '[ -z "$PACKAGE" ] ls "$INST_DIR/stow/current"'
  - '[ -z "$PACKAGE" ] ./bin/stow-get list'
  - '[ -z "$PACKAGE" ] ./bin/stow-get packages'
  - '[ -z "$PACKAGE" ] ./bin/stow-get info screen'
  - '[ -z "$PACKAGE" ] ./bin/stow-get latest wget'
  - '[ -z "$PACKAGE" ] ./bin/stow-get latest openssl'
  - '[ -z "$PACKAGE" ] ./bin/stow-get install -t gnu wget'
  - '[ -z "$PACKAGE" ] ./bin/stow-get install -c ./conf_file -d ./conf_dir'
  - '[ -z "$PACKAGE" ] echo "target_postfix=test" >> share/stow-get/autoconf.sh'
  - '[ -z "$PACKAGE" ] ./bin/stow-get install autoconf'
  - '[ -z "$PACKAGE" ] ls "$INST_DIR/stow"'
  - '[ -z "$PACKAGE" ] ./bin/stow-get cleanup'
  - '[ -z "$PACKAGE" ] ls "$INST_DIR/stow"'
  - '[ -z "$PACKAGE" ] ls "$INST_DIR/stow/current"'

