os:
  - linux
  - osx
language: ruby
before_install:
  - export INST_DIR="$HOME/usr/local"
  - export PATH="$INST_DIR/bin:$PATH"
  - export LD_LIBRARY_PATH="$INST_DIR/lib64:$INST_DIR/lib:$LD_LIBRARY_PATH"
install:
  - echo "PACKAGES=(git screen vim)" > ~/.stow-get
  - echo "PACKAGES=(nano)" > ~/.stow-get
  - mkdir conf_dir
  - echo "PACKAGES=(nano)" > ./conf_file
  - echo "isnt_type=gnu" > ./conf_dir/wdiff.sh
script:
  - ./bin/stow-get help
  - ./bin/stow-get version
  - ./bin/stow-get install -V
  - ./bin/stow-get install $(ls share/stow-get/*sh|cut -d"/" -f3|sed "s/.sh$//")
  - ls "$INST_DIR/stow"
  - ls "$INST_DIR/stow/current"
  - ./bin/stow-get uninstall screen
  - ls "$INST_DIR/stow"
  - ls "$INST_DIR/stow/current"
  - ./bin/stow-get list
  - ./bin/stow-get packages
  - ./bin/stow-get info screen
  - ./bin/stow-get latest wget
  - ./bin/stow-get install -t gnu wget
  - ./bin/stow-get install -c ./conf_file -d ./conf_dir
  - echo "target_postfix=test" >> share/stow-get/autoconf.sh
  - ./bin/stow-get install autoconf
  - ls "$INST_DIR/stow"
  - ./bin/stow-get cleanup
  - ls "$INST_DIR/stow"
  - ls "$INST_DIR/stow/current"
